development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://grrzboiywjqcdm:7a994b5986ab80d023cf0c6083f41beadadfa48ed1f19d3c3eafb3098586b3b1@ec2-174-129-227-116.compute-1.amazonaws.com:5432/d6dj175pqqsbag
  # adapter: redis
  # url: redis://localhost:6379/1
  # channel_prefix: first_production
